In [1]:
import os
import math
import itertools
import numpy as np
import pandas as pd
# PyTorch
import torch
import torchvision

In [2]:
model = torchvision.models.resnet50()
model.fc = torch.nn.Linear(in_features=2048, out_features=102, bias=True)
print(f'd = {len(torch.nn.utils.parameters_to_vector(model.parameters()))}')
model = torchvision.models.vit_b_16()
model.heads = torch.nn.Linear(in_features=768, out_features=102, bias=True)
print(f'd = {len(torch.nn.utils.parameters_to_vector(model.parameters()))}')
model = torchvision.models.convnext_tiny()
model.classifier[2] = torch.nn.Linear(in_features=768, out_features=102, bias=True)
print(f'd = {len(torch.nn.utils.parameters_to_vector(model.parameters()))}')

d = 23717030
d = 85877094
d = 27898566

In [3]:
def check_epochs(df, n, batch_size=128, steps=6000):
    num_batches = math.floor(n/batch_size)
    epochs = int(steps/num_batches)
    if df.shape[0] == epochs:
        return True
    else:
        return False

In [4]:
criterion = 'l2-zero'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'linear_probing_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
print(count)

-1

In [5]:
criterion = 'l2-zero'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
print(count)

-1

In [6]:
criterion = 'l2-sp'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa=1.0_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
print(count)

-1

In [7]:
criterion = 'l2-sp'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
print(count)

-1

In [8]:
criterion = 'ptyl'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_SSL_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
prior_directory = '{home_dir}/resnet50_ssl_prior'
prior_type = 'resnet50_ssl_prior'
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
print(count)

-1

In [9]:
criterion = 'ptyl'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_name=\'{model_name}\' --n={n} --num_workers=0 --random_state={random_state} --save"')
print(count)

-1

In [10]:
criterion = 'l2-sp'
d = 85877094
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ViT_B_16_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
model_arch = 'ViT-B/16'
ns = [510, 1020]
prior_directory = '{home_dir}/vit_b_16_torchvision'
prior_type = 'vit_b_16_torchvision'
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa=1.0_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
print(count)

-1

In [11]:
criterion = 'l2-sp'
d = 85877094
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ViT_B_16_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
model_arch = 'ViT-B/16'
ns = [510, 1020]
prior_directory = '{home_dir}/vit_b_16_torchvision'
prior_type = 'vit_b_16_torchvision'
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
print(count)

-1

In [12]:
criterion = 'l2-sp'
d = 27898566
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ConvNeXt_Tiny_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
model_arch = 'ConvNeXt_Tiny'
ns = [510, 1020]
prior_directory = '{home_dir}/convnext_tiny_torchvision'
prior_type = 'convnext_tiny_torchvision'
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa=1.0_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa=1.0 --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
print(count)

-1

In [13]:
criterion = 'l2-sp'
d = 27898566
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ConvNeXt_Tiny_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
model_arch = 'ConvNeXt_Tiny'
ns = [510, 1020]
prior_directory = '{home_dir}/convnext_tiny_torchvision'
prior_type = 'convnext_tiny_torchvision'
random_states = [1001, 2001, 3001]

count = -1
for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        if not check_epochs(temp_df, n, batch_size=min(128, n), steps=6000):
            count += 1
            print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
    else:
        count += 1
        print(f'    "python ../src/main_Flowers_102.py --batch_size=128 --criterion=\'{criterion}\' --dataset_directory=\'{dataset_directory}\' --ELBo --experiments_directory=\'{experiments_directory}\' --kappa={d/n} --lr_0={lr_0} --model_arch=\'{model_arch}\' --model_name=\'{model_name}\' --n={n} --num_workers=0 --prior_directory=\'{prior_directory}\' --prior_type=\'{prior_type}\' --random_state={random_state} --save"')
print(count)

-1

In [14]:
criterion = 'linear_probing'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
0,linear_probing,linear_probing_kappa=46503.98039215686_lr_0=0....,510,1001,0.003885,0.796273,0.861605
1,linear_probing,linear_probing_kappa=46503.98039215686_lr_0=0....,510,2001,0.003722,0.815586,0.813982
2,linear_probing,linear_probing_kappa=46503.98039215686_lr_0=0....,510,3001,0.003707,0.811354,0.808443
3,linear_probing,linear_probing_kappa=23251.99019607843_lr_0=0....,1020,1001,0.005667,0.881619,0.530901
4,linear_probing,linear_probing_kappa=23251.99019607843_lr_0=0....,1020,2001,0.005521,0.878420,0.528862
5,linear_probing,linear_probing_kappa=23251.99019607843_lr_0=0....,1020,3001,0.005544,0.880536,0.527861

In [15]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,linear_probing,510,(linear_probing_kappa=46503.98039215686_lr_0=0...,"(1001, 2001, 3001)","(0.0038850053159666, 0.0037217868727577, 0.003...","(0.796273410320282, 0.8155858516693115, 0.8113...","(0.8616053829456388, 0.8139822816439571, 0.808...",0.807738,0.008289,0.796273,0.815586,0.828010,0.023863,0.808443,0.861605
1,linear_probing,1020,(linear_probing_kappa=23251.99019607843_lr_0=0...,"(1001, 2001, 3001)","(0.0056666889828721, 0.0055207040613772, 0.005...","(0.8816194534301758, 0.878419816493988, 0.8805...","(0.5309007141878019, 0.528861604894486, 0.5278...",0.880192,0.001329,0.878420,0.881619,0.529208,0.001265,0.527861,0.530901

In [16]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

        criterion     n  test_acc_mean  test_acc_min  test_acc_max
0  linear_probing   510       0.807738      0.796273      0.815586
1  linear_probing  1020       0.880192      0.878420      0.881619

In [17]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

        criterion     n  test_nll_mean  test_nll_min  test_nll_max
0  linear_probing   510       0.828010      0.808443      0.861605
1  linear_probing  1020       0.529208      0.527861      0.530901

In [4]:
criterion = 'l2-zero'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI_alpha=beta'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
12,l2-zero,l2-zero_kappa=46503.98039215686_lr_0=0.001_n=5...,510,1001,1.912104,0.811333,0.917903
13,l2-zero,l2-zero_kappa=46503.98039215686_lr_0=0.001_n=5...,510,2001,2.069878,0.816116,0.780431
14,l2-zero,l2-zero_kappa=46503.98039215686_lr_0=0.001_n=5...,510,3001,1.963534,0.820999,0.826263
15,l2-zero,l2-zero_kappa=23251.99019607843_lr_0=0.001_n=1...,1020,1001,1.684914,0.899304,0.460781
16,l2-zero,l2-zero_kappa=23251.99019607843_lr_0=0.001_n=1...,1020,2001,1.765962,0.905848,0.406940
17,l2-zero,l2-zero_kappa=23251.99019607843_lr_0=0.001_n=1...,1020,3001,1.692850,0.895169,0.447586

In [5]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,l2-zero,510,(l2-zero_kappa=46503.98039215686_lr_0=0.001_n=...,"(1001, 2001, 3001)","(1.9121036249983543, 2.069878485997518, 1.9635...","(0.8113332986831665, 0.8161163330078125, 0.820...","(0.9179025550033556, 0.7804306765236667, 0.826...",0.816150,0.003946,0.811333,0.820999,0.841532,0.057152,0.780431,0.917903
1,l2-zero,1020,(l2-zero_kappa=23251.99019607843_lr_0=0.001_n=...,"(1001, 2001, 3001)","(1.6849137055640129, 1.7659615240845024, 1.692...","(0.8993035554885864, 0.9058483839035034, 0.895...","(0.460780555461603, 0.4069404860975573, 0.4475...",0.900107,0.004397,0.895169,0.905848,0.438436,0.022913,0.406940,0.460781

In [6]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0   l2-zero   510       0.816150      0.811333      0.820999
1   l2-zero  1020       0.900107      0.895169      0.905848

In [7]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0   l2-zero   510       0.841532      0.780431      0.917903
1   l2-zero  1020       0.438436      0.406940      0.460781

In [22]:
criterion = 'l2-sp'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
12,l2-sp,l2-sp_kappa=46503.98039215686_lr_0=0.001_n=510...,510,1001,0.046448,0.833407,0.863215
13,l2-sp,l2-sp_kappa=46503.98039215686_lr_0=0.001_n=510...,510,2001,0.046639,0.841308,0.811356
14,l2-sp,l2-sp_kappa=46503.98039215686_lr_0=0.001_n=510...,510,3001,0.045502,0.834453,0.837070
15,l2-sp,l2-sp_kappa=23251.99019607843_lr_0=0.001_n=102...,1020,1001,0.054888,0.913260,0.480238
16,l2-sp,l2-sp_kappa=23251.99019607843_lr_0=0.001_n=102...,1020,2001,0.055260,0.910293,0.476918
17,l2-sp,l2-sp_kappa=23251.99019607843_lr_0=0.001_n=102...,1020,3001,0.054377,0.910691,0.476438

In [23]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,l2-sp,510,(l2-sp_kappa=46503.98039215686_lr_0=0.001_n=51...,"(1001, 2001, 3001)","(0.0464477505038182, 0.0466387633541051, 0.045...","(0.8334072232246399, 0.8413082957267761, 0.834...","(0.8632149664822355, 0.8113556129527415, 0.837...",0.836389,0.003504,0.833407,0.841308,0.837214,0.021172,0.811356,0.863215
1,l2-sp,1020,(l2-sp_kappa=23251.99019607843_lr_0=0.001_n=10...,"(1001, 2001, 3001)","(0.0548879769006196, 0.0552598641038525, 0.054...","(0.9132604598999025, 0.9102930426597596, 0.910...","(0.4802378222339035, 0.4769175192148856, 0.476...",0.911415,0.001315,0.910293,0.913260,0.477865,0.001690,0.476438,0.480238

In [24]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0     l2-sp   510       0.836389      0.833407      0.841308
1     l2-sp  1020       0.911415      0.910293      0.913260

In [25]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0     l2-sp   510       0.837214      0.811356      0.863215
1     l2-sp  1020       0.477865      0.476438      0.480238

In [26]:
criterion = 'ptyl'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_SSL_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
12,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,1001,0.233813,0.762978,1.136894
13,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,2001,0.157236,0.766447,1.078049
14,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,3001,0.204900,0.761147,1.171967
15,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,1001,0.173270,0.844408,0.729199
16,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,2001,0.150329,0.849285,0.706465
17,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,3001,0.156524,0.848231,0.745308

In [27]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,ptyl,510,(ptyl_kappa=46503.98039215686_lr_0=0.001_n=510...,"(1001, 2001, 3001)","(0.2338131290907953, 0.1572355201489785, 0.204...","(0.7629784345626831, 0.7664468288421631, 0.761...","(1.136893781336716, 1.0780489480889006, 1.1719...",0.763524,0.002198,0.761147,0.766447,1.128970,0.038749,1.078049,1.171967
1,ptyl,1020,(ptyl_kappa=23251.99019607843_lr_0=0.001_n=102...,"(1001, 2001, 3001)","(0.173270314636768, 0.1503289300086451, 0.1565...","(0.8444084525108337, 0.8492854833602905, 0.848...","(0.7291993920549393, 0.7064654536292038, 0.745...",0.847308,0.002095,0.844408,0.849285,0.726991,0.015934,0.706465,0.745308

In [28]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0      ptyl   510       0.763524      0.761147      0.766447
1      ptyl  1020       0.847308      0.844408      0.849285

In [29]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0      ptyl   510       1.128970      1.078049      1.171967
1      ptyl  1020       0.726991      0.706465      0.745308

In [30]:
criterion = 'ptyl'
d = 23717030
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
12,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,1001,0.046447,0.833674,0.863104
13,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,2001,0.046643,0.841947,0.811153
14,ptyl,ptyl_kappa=46503.98039215686_lr_0=0.001_n=510_...,510,3001,0.045500,0.834453,0.837092
15,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,1001,0.054886,0.913312,0.480283
16,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,2001,0.055261,0.909613,0.476892
17,ptyl,ptyl_kappa=23251.99019607843_lr_0=0.001_n=1020...,1020,3001,0.054378,0.910691,0.476313

In [31]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,ptyl,510,(ptyl_kappa=46503.98039215686_lr_0=0.001_n=510...,"(1001, 2001, 3001)","(0.0464473451148061, 0.0466425692143977, 0.045...","(0.8336737751960754, 0.8419470191001892, 0.834...","(0.8631041730942037, 0.8111529296676323, 0.837...",0.836691,0.003730,0.833674,0.841947,0.837116,0.021209,0.811153,0.863104
1,ptyl,1020,(ptyl_kappa=23251.99019607843_lr_0=0.001_n=102...,"(1001, 2001, 3001)","(0.0548855657393441, 0.0552609157401557, 0.054...","(0.9133120775222778, 0.909613072872162, 0.9106...","(0.4802829160320653, 0.4768920265262951, 0.476...",0.911205,0.001553,0.909613,0.913312,0.477829,0.001751,0.476313,0.480283

In [32]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0      ptyl   510       0.836691      0.833674      0.841947
1      ptyl  1020       0.911205      0.909613      0.913312

In [33]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0      ptyl   510       0.837116      0.811153      0.863104
1      ptyl  1020       0.477829      0.476313      0.480283

In [34]:
criterion = 'l2-sp'
d = 85877094
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ViT_B_16_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
0,l2-sp,l2-sp_kappa=168386.45882352942_lr_0=0.1_n=510_...,510,1001,0.003023,0.793513,0.929795
1,l2-sp,l2-sp_kappa=168386.45882352942_lr_0=0.1_n=510_...,510,2001,0.003039,0.840393,0.731671
2,l2-sp,l2-sp_kappa=168386.45882352942_lr_0=0.1_n=510_...,510,3001,0.003040,0.779803,1.029982
3,l2-sp,l2-sp_kappa=84193.22941176471_lr_0=0.1_n=1020_...,1020,1001,0.004487,0.884972,0.551350
4,l2-sp,l2-sp_kappa=84193.22941176471_lr_0=0.1_n=1020_...,1020,2001,0.004279,0.896406,0.482004
5,l2-sp,l2-sp_kappa=84193.22941176471_lr_0=0.1_n=1020_...,1020,3001,0.004550,0.894760,0.499806

In [35]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,l2-sp,510,(l2-sp_kappa=168386.45882352942_lr_0=0.1_n=510...,"(1001, 2001, 3001)","(0.0030233223318104, 0.0030386100380736, 0.003...","(0.7935128211975098, 0.8403925895690918, 0.779...","(0.9297949003168076, 0.7316712458010787, 1.029...",0.804569,0.025942,0.779803,0.840393,0.897149,0.123953,0.731671,1.029982
1,l2-sp,1020,(l2-sp_kappa=84193.22941176471_lr_0=0.1_n=1020...,"(1001, 2001, 3001)","(0.0044866291119479, 0.004278663981925, 0.0045...","(0.8849722743034363, 0.8964061737060547, 0.894...","(0.5513501286335202, 0.4820044740330526, 0.499...",0.892046,0.005047,0.884972,0.896406,0.511053,0.029406,0.482004,0.551350

In [36]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0     l2-sp   510       0.804569      0.779803      0.840393
1     l2-sp  1020       0.892046      0.884972      0.896406

In [37]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0     l2-sp   510       0.897149      0.731671      1.029982
1     l2-sp  1020       0.511053      0.482004      0.551350

In [38]:
criterion = 'l2-sp'
d = 27898566
dataset_directory = '{home_dir}/Flowers_102'
experiments_directory = '{home_dir}/data-emphasized-ELBo/experiments/retrained_Flowers_102_ConvNeXt_Tiny_VI'
lr_0s = [0.1, 0.01, 0.001, 0.0001]
ns = [510, 1020]
random_states = [1001, 2001, 3001]

columns = ['criterion', 'model_name', 'n', 'random_state', 'train_loss', 'test_acc', 'test_nll']
retrained_df = pd.DataFrame(columns=columns)

for lr_0, n, random_state in itertools.product(lr_0s, ns, random_states):
    model_name = f'{criterion}_kappa={d/n}_lr_0={lr_0}_n={n}_random_state={random_state}'
    if os.path.exists(f'{experiments_directory}/{model_name}.csv'):
        temp_df = pd.read_csv(f'{experiments_directory}/{model_name}.csv')
        row = [criterion, model_name, n, random_state, temp_df.train_loss.values[-1], temp_df.val_or_test_acc.values[-1], temp_df.val_or_test_nll.values[-1]]
        retrained_df.loc[len(retrained_df)] = row
    
min_indices = retrained_df.groupby(['criterion', 'n', 'random_state'])['train_loss'].idxmin()
retrained_df = retrained_df.loc[min_indices]

retrained_df

,criterion,model_name,n,random_state,train_loss,test_acc,test_nll
0,l2-sp,l2-sp_kappa=54703.07058823529_lr_0=0.1_n=510_r...,510,1001,0.005832,0.868424,0.640800
1,l2-sp,l2-sp_kappa=54703.07058823529_lr_0=0.1_n=510_r...,510,2001,0.005703,0.881999,0.572550
2,l2-sp,l2-sp_kappa=54703.07058823529_lr_0=0.1_n=510_r...,510,3001,0.005868,0.890430,0.530167
3,l2-sp,l2-sp_kappa=27351.535294117646_lr_0=0.1_n=1020...,1020,1001,0.007365,0.938762,0.308665
4,l2-sp,l2-sp_kappa=27351.535294117646_lr_0=0.1_n=1020...,1020,2001,0.007476,0.941599,0.295506
5,l2-sp,l2-sp_kappa=27351.535294117646_lr_0=0.1_n=1020...,1020,3001,0.007598,0.941168,0.288775

In [39]:
grouped_df = retrained_df.groupby(['criterion', 'n']).agg(lambda x: tuple(x))
columns = ['test_acc', 'test_nll']
for column in columns:
    grouped_df[f'{column}_mean'] = grouped_df[column].apply(lambda item: np.mean(item))
    grouped_df[f'{column}_std'] = grouped_df[column].apply(lambda item: np.std(item))
    grouped_df[f'{column}_min'] = grouped_df[column].apply(lambda item: np.min(item))
    grouped_df[f'{column}_max'] = grouped_df[column].apply(lambda item: np.max(item))
grouped_df = grouped_df.reset_index()
grouped_df

,criterion,n,model_name,random_state,train_loss,test_acc,test_nll,test_acc_mean,test_acc_std,test_acc_min,test_acc_max,test_nll_mean,test_nll_std,test_nll_min,test_nll_max
0,l2-sp,510,(l2-sp_kappa=54703.07058823529_lr_0=0.1_n=510_...,"(1001, 2001, 3001)","(0.0058316533722202, 0.0057025078351737, 0.005...","(0.8684244155883789, 0.881999135017395, 0.8904...","(0.6407998105119397, 0.5725501998786442, 0.530...",0.880285,0.009065,0.868424,0.890430,0.581172,0.045575,0.530167,0.640800
1,l2-sp,1020,(l2-sp_kappa=27351.535294117646_lr_0=0.1_n=102...,"(1001, 2001, 3001)","(0.0073645753747619, 0.0074756661059298, 0.007...","(0.938761830329895, 0.9415990710258484, 0.9411...","(0.3086650833626058, 0.2955056260517871, 0.288...",0.940510,0.001248,0.938762,0.941599,0.297649,0.008260,0.288775,0.308665

In [40]:
grouped_df[['criterion', 'n', 'test_acc_mean', 'test_acc_min', 'test_acc_max']]

  criterion     n  test_acc_mean  test_acc_min  test_acc_max
0     l2-sp   510       0.880285      0.868424      0.890430
1     l2-sp  1020       0.940510      0.938762      0.941599

In [41]:
grouped_df[['criterion', 'n', 'test_nll_mean', 'test_nll_min', 'test_nll_max']]

  criterion     n  test_nll_mean  test_nll_min  test_nll_max
0     l2-sp   510       0.581172      0.530167      0.640800
1     l2-sp  1020       0.297649      0.288775      0.308665